name: Display Model Score

on :
  pull_request:
    branches:
      - main

jobs:
  display-model-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version:3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create model
        run:
          python train.py

      - name: Test model and display score
        run: |
          OUTPUT=$(python test.py)
          echo "Score:"
          echo "$OUTPUT"

